### ISSUE TITLE
Question on the plugin that uses HAConvGNN to generate documentation

### ISSUE THREAD

**Issue by Tamal-Mondal** [liubest/HAConvGNN#3]
The exact line from the paper is "The plugin then reads the contents from the focused cell and its adjacent cells, and sends the content to the backend". As the model considers a maximum of 4 code cells,

1. can you please explain how the front end decides the 4 code cells to send to the backend?
2. Are these 4 code cells need to be consecutive?
3. Is it mandatory that none of the 4 code cells can have any markdown? if that's the case, how does the plugin decide which code cell to skip and for which to trigger documentation?

**Comment by xuyeliu** [comment]
Thanks for your question. 
1. I will select first four code cells between pre-Markdown(The first Markdown cell above these code cells) and post-Markdown(The first Markdown cell below these code cells). If there are more than 4 code cells between these two Markdown cells, I will keep the first four code cells. I will fill with empty sequence if there is lessthan four code sequences.
2. Yes
3. that is for training step. In the plugin, we just based on that 4 code cells to generate pre-Markdown

**Comment by Tamal-Mondal** [comment]
Thanks for clarifying.
